# Generated by Django 3.2 on 2021-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_health', models.IntegerField()),
                ('max_mana', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gold', models.IntegerField()),
            ],
        ),
    ]
