# Generated by Django 3.2 on 2021-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20210415_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(),
        ),
    ]
