# Generated by Django 3.2 on 2021-04-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210417_1925'),
        ('characters', '0007_alter_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.weapon'),
        ),
    ]
