# Generated by Django 3.2 on 2021-04-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_weapon'),
        ('characters', '0009_remove_character_weapon_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapon_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.weapon'),
        ),
    ]
