# Generated by Django 3.2 on 2021-04-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_weapon'),
        ('characters', '0012_auto_20210418_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='spell_equipped',
            field=models.ManyToManyField(blank=True, to='items.Spell'),
        ),
    ]
