# Generated by Django 3.2 on 2021-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_alter_character_spell_equipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='max_mana',
            field=models.IntegerField(default=20),
        ),
    ]
