# Generated by Django 3.2 on 2021-04-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210419_2135'),
        ('characters', '0014_alter_character_max_mana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor_equipped',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.armor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spell_equipped',
            field=models.ManyToManyField(default=1, to='items.Spell'),
        ),
    ]
