# Generated by Django 3.2 on 2021-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_potion_quantity'),
        ('characters', '0015_auto_20210419_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='potions_equipped',
            field=models.ManyToManyField(to='items.Potion'),
        ),
    ]
