# Generated by Django 3.2 on 2021-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20210427_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potionquantity',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
