# Generated by Django 3.2 on 2021-04-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_potion_quantity'),
        ('characters', '0018_alter_potionquantity_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='potionquantity',
            unique_together={('character', 'potion')},
        ),
    ]
