# Generated by Django 3.2 on 2021-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_alter_potionquantity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=50),
        ),
    ]
