# Generated by Django 3.2 on 2021-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_character_current_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_mana',
            field=models.IntegerField(default=20),
        ),
    ]
