# Generated by Django 3.2 on 2021-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_auto_20210503_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exp_to_lvl_up',
            field=models.IntegerField(default=50),
        ),
    ]
