# Generated by Django 3.2 on 2022-02-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_alter_character_exp_to_lvl_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterToPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
