# Generated by Django 3.2 on 2022-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_charactertoplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertoplay',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
