# Generated by Django 3.2 on 2021-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210414_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='health',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_melee_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_ranged_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_melee_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_ranged_dmg',
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_melee_dmg', models.IntegerField()),
                ('max_melee_dmg', models.IntegerField()),
                ('min_ranged_dmg', models.IntegerField()),
                ('name', models.ManyToManyField(to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('name', models.ManyToManyField(to='items.Item')),
            ],
        ),
    ]
