# Generated by Django 3.2 on 2021-04-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210414_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='defence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_melee_dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_ranged_dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='min_melee_dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='min_ranged_dmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='defence',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='health',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='name',
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
    ]
