# Generated by Django 3.2 on 2021-04-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210414_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='health',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_melee_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_ranged_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_melee_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_ranged_dmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='name',
        ),
        migrations.AddField(
            model_name='armor',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', ''), ('Weapons', 'Weapons'), ('Armors', 'Armors'), ('Spells', 'Spells')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
