# Generated by Django 3.2 on 2021-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210414_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='min_ranged_dmg',
        ),
        migrations.AddField(
            model_name='armor',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='spell',
            name='max_spell_dmg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='min_spell_dmg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
