# Generated by Django 3.2 on 2021-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210415_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='max_spell_dmg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='min_spell_dmg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
