# Generated by Django 3.2 on 2021-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210415_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='level_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
