# Generated by Django 3.2 on 2021-04-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_delete_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_melee_dmg', models.IntegerField()),
                ('max_melee_dmg', models.IntegerField()),
                ('level_required', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
