# Generated by Django 3.2 on 2021-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='dmg_type',
            field=models.CharField(default='fire', max_length=50),
        ),
        migrations.AddField(
            model_name='spell',
            name='mana_cost',
            field=models.IntegerField(default=0),
        ),
    ]
