# Generated by Django 3.2 on 2021-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210419_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
