# Generated by Django 3.2 on 2021-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_potion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='level_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='potion',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
