# Generated by Django 3.2 on 2021-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_potion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
