# Generated by Django 3.2 on 2021-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_potion_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potion',
            name='quantity',
        ),
    ]
