# Generated by Django 3.2 on 2021-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('min_dmg', models.IntegerField()),
                ('max_dmg', models.IntegerField()),
                ('immune', models.CharField(max_length=50)),
                ('frozen', models.BooleanField(default=False)),
            ],
        ),
    ]
