# Generated by Django 3.2 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_monster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='type',
            field=models.CharField(choices=[('Spider', 'Spider'), ('Rat', 'Rat'), ('Ogre', 'Ogre'), ('Troll', 'Troll')], max_length=50),
        ),
    ]
