# Generated by Django 3.2 on 2021-04-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_alter_monster_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='max_health',
            new_name='health',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='min_health',
        ),
    ]
