# Generated by Django 3.2 on 2021-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0004_auto_20210428_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(null=True),
        ),
    ]
