# Generated by Django 3.2 on 2021-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_alter_monster_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='max_dmg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='min_dmg',
            field=models.IntegerField(null=True),
        ),
    ]
