# Generated by Django 3.2 on 2021-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0014_auto_20210429_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_dmg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='min_dmg',
            field=models.IntegerField(),
        ),
    ]
