# Generated by Django 3.2 on 2021-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0015_auto_20210429_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='experience_given',
            field=models.IntegerField(default=1),
        ),
    ]
